### ISSUE TITLE
Listing of Netdex Users

### ISSUE THREAD

**Issue by HerrMotz** [netdexco/Netdex#17]
#A list of popular Netdex users
### Rating
 - Followers
 - Paragraphs
 - Likes

**Comment by timmyrs** [comment]
I will change up the system, but will try to make it until month end.

**Comment by timmyrs** [comment]
# Proprosal

## Idea

+ How popular are depends on your active followers percentage (See Calculation)
+ You are completely hidden with 0%
+ You will get 0% when you are not searchable

## Calculation

Popularity is measured in percent: `((100/followers)*(likes/paragraphs))%`

## Placement

+ A card recommending that you find people to follow using this feature
+ "Discover" on the footer

**Comment by timmyrs** [comment]
Let's see how it goes.
Gonna translate it in a second.
